[run]
  deadline = "5m"
  skip-files = []

[linters-settings]

  [linters-settings.govet]
    check-shadowing = true

  [linters-settings.gocyclo]
    min-complexity = 12.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 3.0

  [linters-settings.misspell]
    locale = "US"

[linters]
  enable = ["vet", "gofmt", "deadcode", "varcheck", "structcheck", "misspell", "errcheck", "gosimple", "govet"]
  disable = ["ineffassign"]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = []
  [[issues.exclude-rules]]
    path = "cmd/swagger-codegen/main.go"
    linters = ["errcheck"]
  [[issues.exclude-rules]]
    text = "Error return value of `g.SetCurrentView` is not checked"
    linters = ["errcheck"]
  [[issues.exclude-rules]]
    text = """declaration of "err" shadows declaration at *"""
    linters = ["govet"]

