sudo: required
language: generic
addons:
  apt:
    packages:
    - docker-ce
services:
- docker
script:
- bash ./scripts/ci.sh

before_deploy:
- git tag "v1.0.$TRAVIS_BUILD_NUMBER"
- export BODY=$(git log -1  --pretty='%s')

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: cQ6o4ThE2IEfMjhKYch1bnOtTPO3GAmEdLfhrJebYiLRXiL4o/etOvHC89CSvrgbokShC57UL7h+IDD9JnRyk5H6hcNi3sLmYe5uCg205GjYcuxwCxAp9iuUOnwiiH0R7FegXj1+YUb/ockSO9cMispObC+SHrnq802BeRPyXrVQ3ECwXuQLbJp/0Ib9ouBhAVo2vti6RjFqOLcUpBYfN4uIbZDoxjIyXDvtuP2/LXnZ5WZw4COTM8ut2Kc1HKr1Ci97PxWPahXKW+9eyD30IXs2qmjd/gEamftXifXbAsaZlC9Gex4YpvXMGPytJm5TCH2MTZLAKwGKelwWLIj8FwlBt6YZbIcuLfIK1PZQBdohW8UXdddh//eplDNtn9NBqEk+qww0R7SUIvvND0NFokesTs/vBQ17JJXCRbzhl9gLMYvaifYIUCP7UyXZdpmHAKHlLmbkqBCcLspoppFNoneG/vx3jbb2ptubdYqmb5pR9W/FKxQBsSVqNcH8S2+yFcSnTjK/idJ7gnLNsddqdTdbBfIsmpOdHJR03Ka5qQ/c0P1v6qkiO/VxAdcFHiybyNaQ/y8cEJ4MX+x82ZHAd/tyZIwuxch/VCDSHrt2KTMtVMq3O5Tk2v8oDEzeYudJYUMsqCZmyzNrEu3aGO2N16EnzRt66Me5SDfExCWX8Kw=
  file_glob: true
  file: bin/*
  body: ${BODY}
  on:
    repo: lawrencegripper/azbrowse
    branch: master