version: 2
jobs:
  build:
    docker:
      - image: golang:1.11.5
    working_directory: /go/src/github.com/lawrencegripper/azbrowse
    steps:
      - checkout 
      - setup_remote_docker
      - run:
          name: Should publish?
          command: if [ -z $CIRCLE_PR_NUMBER ] && [[ $CIRCLE_BRANCH == "master" ]]; then export PUBLISH=true; echo "On master setting PUBLISH=true"; else echo "Skipping publish as is from PR: $CIRCLE_PR_NUMBER or not master BRANCH: $CIRCLE_BRANCH"; fi
      - run: 
          name: Build and Publish
          command: export BUILD_NUMBER=${CIRCLE_BUILD_NUM} && bash -f /go/src/github.com/lawrencegripper/azbrowse/scripts/ci.sh