# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: golang:1.11.5
    working_directory: /go/src/github.com/lawrencegripper/azbrowse
    steps:
      - checkout 
      - setup_remote_docker
      - run: bash -c "cd /tmp && curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-18.06.3-ce.tgz && tar --strip-components=1 -xvzf docker-18.06.3-ce.tgz -C /usr/local/bin"
      - run: export BUILD_NUMBER=${CIRCLE_BUILD_NUM} && bash -f /go/src/github.com/lawrencegripper/azbrowse/scripts/install_release_tools.sh && bash -f /go/src/github.com/lawrencegripper/azbrowse/scripts/release.sh